on:
  push:
    branches:
      - master

jobs:
  deploy-aws:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Prepare java
        uses: actions/setup-java@v1
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@3.5
        with:
          cli: 1.10.3.855 # Clojure CLI based on tools.deps

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Push Datomic ions
        run: clojure -A:ion-dev '{:op :push}'

      - name: Deploy Datomic ions
        run: |
          clojure -A:ion-dev '{:op :deploy, :group "clj-ynab-prod", :rev "${{ github.sha }}"}'
